

import java.sql.DatabaseMetaData;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import org.omg.CORBA.Object;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nermin
 */
public class FormUposlenici extends javax.swing.JFrame {

    /**
     * Creates new form FormUposlenici
     */
    public FormUposlenici() {
        initComponents();
    }
    public static int id;
  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableUposlenici = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        imeTxt = new javax.swing.JTextField();
        Pronadji = new javax.swing.JButton();
        btnIzmjeniUposlenika = new javax.swing.JButton();
        btnDodajUposlenika = new javax.swing.JButton();
        btnObrisiUposlenika = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableUposlenici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableUposlenici);

        jLabel1.setText("Ime uposlenika");

        imeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imeTxtActionPerformed(evt);
            }
        });

        Pronadji.setText("Pronadji");
        Pronadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PronadjiActionPerformed(evt);
            }
        });

        btnIzmjeniUposlenika.setText("Izmjeni uposlenika");
        btnIzmjeniUposlenika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmjeniUposlenikaActionPerformed(evt);
            }
        });

        btnDodajUposlenika.setText("Dodaj uposlenika");
        btnDodajUposlenika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajUposlenikaActionPerformed(evt);
            }
        });

        btnObrisiUposlenika.setText("Obriši uposlenika");
        btnObrisiUposlenika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiUposlenikaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDodajUposlenika, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(btnIzmjeniUposlenika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnObrisiUposlenika, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pronadji, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(imeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pronadji))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDodajUposlenika, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIzmjeniUposlenika, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnObrisiUposlenika, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PronadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PronadjiActionPerformed
       
        List<Uposlenik> uposlenici=null;
        
        try{
        
        String imeTextBox=imeTxt.getText();
        
        if(imeTextBox !=null &&imeTextBox.trim().length()>0){
            uposlenici=Baza.nadjiUposlenog(imeTextBox);
        }
        else
            uposlenici=Baza.sviUposlenici();
        
        ModelTabelaUposlenika Model=new ModelTabelaUposlenika(uposlenici);
        tableUposlenici.setModel(Model);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(tableUposlenici, e.getCause());
        }
    }//GEN-LAST:event_PronadjiActionPerformed

    private void imeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imeTxtActionPerformed

    private void btnDodajUposlenikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajUposlenikaActionPerformed

       NoviUposlenik noviUposlenik=new NoviUposlenik(FormUposlenici.this,true);
       noviUposlenik.setVisible(true);
    }//GEN-LAST:event_btnDodajUposlenikaActionPerformed

    private void btnIzmjeniUposlenikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmjeniUposlenikaActionPerformed
       
        int red=tableUposlenici.getSelectedRow();
        FormUposlenici formUposlenici = null;
        
        if(red<0){
            JOptionPane.showMessageDialog(FormUposlenici.this, "Morate selektovati uposlenika!!!");
            return;
        }
        
    
        Uposlenik tempUposlenik=ModelTabelaUposlenika.uposlenici.get(tableUposlenici.convertRowIndexToModel(red));
     
        IzmjeniUposlenika izmjeniUposlenika=new IzmjeniUposlenika(formUposlenici,true,tempUposlenik);
        
        id=tempUposlenik.getId();
        izmjeniUposlenika.setVisible(true);
        
        


     

        
        
        
        
    }//GEN-LAST:event_btnIzmjeniUposlenikaActionPerformed

    private void btnObrisiUposlenikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiUposlenikaActionPerformed
        
        int red=tableUposlenici.getSelectedRow();
        FormUposlenici formUposlenici = null;
        
        if(red<0){
            JOptionPane.showMessageDialog(FormUposlenici.this, "Morate selektovati uposlenika!!!");
            return;
        }

        Uposlenik tempUposlenik=ModelTabelaUposlenika.uposlenici.get(tableUposlenici.convertRowIndexToModel(red));
        
        
        int dialogButton=JOptionPane.YES_NO_OPTION;
       int odgovor= JOptionPane.showConfirmDialog(FormUposlenici.this, "Jeste li sigurni da želite obristai selektovanog upolenika?","Upozorenje",dialogButton);
        
        if(odgovor==JOptionPane.YES_OPTION){
            
            
            try {
                Baza.brisiUposlenika(tempUposlenik.getId());
                
            } catch (SQLException ex) {
                Logger.getLogger(FormUposlenici.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        else{
           return;
        }
          
       
        
    }//GEN-LAST:event_btnObrisiUposlenikaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUposlenici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUposlenici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUposlenici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUposlenici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUposlenici().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Pronadji;
    private javax.swing.JButton btnDodajUposlenika;
    private javax.swing.JButton btnIzmjeniUposlenika;
    private javax.swing.JButton btnObrisiUposlenika;
    private javax.swing.JTextField imeTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tableUposlenici;
    // End of variables declaration//GEN-END:variables
}
