

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nermin
 */
public class IzmjeniUposlenika extends javax.swing.JDialog {

    /**
     * Creates new form IzmjeniUposlenika
     * @param parent
     * @param modal
     */
    
    

    public IzmjeniUposlenika(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public IzmjeniUposlenika(java.awt.Frame parent,boolean modal,Uposlenik uposlenik){
        super(parent, modal);
        initComponents();
        txtIme.setText(uposlenik.getIme());
        txtAdresa.setText(uposlenik.getAdresa());
        txtGodine.setText(String.valueOf(uposlenik.getBrojGodina()));
        txtDohodak.setText(String.valueOf(uposlenik.getVisinaDohotka()));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIme = new javax.swing.JLabel();
        lblAdresa = new javax.swing.JLabel();
        lblGodine = new javax.swing.JLabel();
        lblDohodak = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        txtAdresa = new javax.swing.JTextField();
        txtGodine = new javax.swing.JTextField();
        txtDohodak = new javax.swing.JTextField();
        btnIzmjeni = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Izmjeni uposlenika");

        lblIme.setText("Ime:");

        lblAdresa.setText("Adresa:");

        lblGodine.setText("Godine:");

        lblDohodak.setText("Dohodak:");

        btnIzmjeni.setText("Izmjeni");
        btnIzmjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmjeniActionPerformed(evt);
            }
        });

        btnOtkazi.setText("Otkazi");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIme)
                    .addComponent(lblAdresa)
                    .addComponent(lblGodine)
                    .addComponent(lblDohodak))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDohodak, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnIzmjeni)
                        .addGap(18, 18, 18)
                        .addComponent(btnOtkazi))
                    .addComponent(txtIme)
                    .addComponent(txtGodine)
                    .addComponent(txtAdresa, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIme)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdresa)
                    .addComponent(txtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGodine)
                    .addComponent(txtGodine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDohodak)
                    .addComponent(txtDohodak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzmjeni)
                    .addComponent(btnOtkazi))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmjeniActionPerformed

     
        String ime=txtIme.getText();
        String adresa=txtAdresa.getText();
        int godine=Integer.parseInt(txtGodine.getText());
        int dohodak=Integer.parseInt(txtDohodak.getText());
        
        Uposlenik tempUposlenik=new Uposlenik(FormUposlenici.id, ime, adresa, godine, dohodak);
        
        try {
            Baza.izmjeniUposlenika(tempUposlenik);
        } catch (SQLException ex) {
            Logger.getLogger(IzmjeniUposlenika.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(false);
        
     
    }//GEN-LAST:event_btnIzmjeniActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
       setVisible(false);
    }//GEN-LAST:event_btnOtkaziActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IzmjeniUposlenika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IzmjeniUposlenika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IzmjeniUposlenika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IzmjeniUposlenika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IzmjeniUposlenika dialog = new IzmjeniUposlenika(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmjeni;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JLabel lblAdresa;
    private javax.swing.JLabel lblDohodak;
    private javax.swing.JLabel lblGodine;
    private javax.swing.JLabel lblIme;
    private javax.swing.JTextField txtAdresa;
    private javax.swing.JTextField txtDohodak;
    private javax.swing.JTextField txtGodine;
    private javax.swing.JTextField txtIme;
    // End of variables declaration//GEN-END:variables
}
